### ISSUE TITLE
PGSQL to MYSQL Memory Limit With a 16 Gb Dump

### ISSUE THREAD

**Issue by SubZero5** [ayunaoss/pg2mysql#1]
Hi,

I have a dump to be converted from PostGreSQL to MySQL.
But strangely it inserts whole table in a single query like:

`COPY cTn (uid, nid, fa, ..., misc) FROM stdin;`
`...<tab>...<tab>...<tab>...<tab>...<NULL>`
`...<tab>...<tab>...<tab>...<tab>...<NULL>`
`... (like ~500.000 lines like this)`
`...<tab>...<tab>...<tab>...<tab>...<NULL>`

How do I convert it with only a couple of Mb of RAM?

**Comment by ayunaoss** [comment]
Hi, I need to check this out as I'm not finding time to maintain this as of now. It would be great if you can checkout the source code in the meantime.

**Comment by SubZero5** [comment]
Unfortunately, I have no knowledge in postgresql but I might have a strange side solution for you:

I may get and parse every 50 or 100 or 150 or ... or 500 or 1000 etc. lines so that the memory would not get clogged up importing the whole tab delimited file maby...

Parsing the whole insert part by part might be less memory intensive...

Just thinking aloud here...

**Comment by ayunaoss** [comment]
> Unfortunately, I have no knowledge in postgresql but I might have a strange side solution for you:
> 
> I may get and parse every 50 or 100 or 150 or ... or 500 or 1000 etc. lines so that the memory would not get clogged up importing the whole tab delimited file maby...
> 
> Parsing the whole insert part by part might be less memory intensive...
> 
> Just thinking aloud here...

Sounds good! Unfortunately it might not be possible for me to work on this as of now and, I would be difficult to provide a timeline. Sorry about that!

**Comment by ayunaoss** [comment]
> Hi,
> 
> I have a dump to be converted from PostGreSQL to MySQL.
> But strangely it inserts whole table in a single query like:
> 
> `COPY cTn (uid, nid, fa, ..., misc) FROM stdin;`
> `...<tab>...<tab>...<tab>...<tab>...<NULL>`
> `...<tab>...<tab>...<tab>...<tab>...<NULL>`
> `... (like ~500.000 lines like this)`
> `...<tab>...<tab>...<tab>...<tab>...<NULL>`
> 
> How do I convert it with only a couple of Mb of RAM?

Hi, I would strongly suggest you to go through the README file and follow the links there. The actual work is done by folks form lighbox.org as mentioned in the credits. You may even try connecting with them for any help. Closing the issue for now.
